name = "pay-in-crypto-bot"
compatibility_date = "2024-07-20"
main = "src/index.ts"
keep_vars = true

[observability.logs]
enabled = true

[vars]
TELEGRAM_SECRET_TOKEN = "53o7vzSTrZaZYA5R12jtrL7MdLZXBJs22R0F"